### ISSUE TITLE
The training speed is too slow.

### ISSUE THREAD

**Issue by HaoRayx** [Jixuan-Fan/Momentum-GS#2]
I used 4 RTX3090 graphics cards to train  rubble, and it took 9 hours in the end. Is this normal?

**Comment by Jixuan-Fan** [comment]
> I used 4 RTX3090 graphics cards to train rubble, and it took 9 hours in the end. Is this normal?

Hi HaoRayx,
This is possible due to the limitations of SSD read and write speeds. The block needs to switch directly between the disk and the GPU in our current implementation, which requires a lot of I/O time. For reference, we use 8 GPUs to train Rubble in about 3 hours, while training with 4 GPUs takes around 7 hours.
As for why the blocks are moved to disk instead of memory, we found that transferring them to memory will causes unknown issues that result in a decline in reconstruction quality. Despite our best efforts and numerous attempts with various methods, we could not resolve the problem. If you have a solution, please let me know!

**Comment by HaoRayx** [comment]
Thanks for replying!
